# Usa la imagen base de Node
FROM node:14

# Establece el directorio de trabajo
WORKDIR /app

# Copia el package.json y el package-lock.json
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto de la aplicación
COPY . .

# Expone el puerto de React
EXPOSE 3000

# Ejecuta el servidor de desarrollo
CMD ["npm", "start"]