save 900 1          # Guardar la base de datos después de 900 segundos (15 minutos) si al menos 1 clave ha cambiado
save 300 10         # Guardar después de 300 segundos (5 minutos) si al menos 10 claves han cambiado
save 60 10000       # Guardar después de 60 segundos si al menos 10000 claves han cambiado
stop-writes-on-bgsave-error yes # Detener las escrituras si falla el bgsave (guardado en segundo plano)
rdbcompression yes    # Comprimir los archivos RDB
dbfilename dump.rdb   # Nombre del archivo RDB
dir /data             # Directorio donde se guardan los archivos RDB
appendonly yes        # Activar la persistencia AOF
appendfilename "appendonly.aof" # Nombre del archivo AOF
appendfsync everysec  # Frecuencia con la que se escriben los comandos en el disco (always, everysec, no)
# auto-aof-rewrite-percentage 100 # Reescritura automática del AOF cuando su tamaño crezca en este porcentaje
# auto-aof-rewrite-min-size 64mb  # Tamaño mínimo para iniciar la reescritura automática del AOF
port 6379             # Puerto en el que escucha Redis (debería coincidir con el mapeo de puertos de Docker)
bind 0.0.0.0          # Escuchar en todas las interfaces (necesario para acceder desde fuera del contenedor)
requirepass your_password_here # Requerir una contraseña para acceder a Redis (¡muy recomendado para producción!)
maxmemory <bytes>     # Límite de memoria que Redis puede usar
maxmemory-policy volatile-lru # Política de desalojo de memoria cuando se alcanza el límite